BlogApp/Controllers/BlogController.cs
using BlogApp.Data;
using BlogApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogApp.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index(int sayfa = 1, string aranan = "", string tittleSiralama = "", string kategoriFiltreleme = "", string etiketFiltreleme = "", string yayinFiltreleme = "")
        {
            var db = new SqlContext();
            var blogs = db.Blogs.Include(x => x.BlogCategory)
                .Include(x => x.BlogTags)
                .Where(x => EF.Functions.Like(x.Tittle, "%" + aranan + "%"))
                .Where(x => EF.Functions.Like(x.BlogCategory.CategoryName, "%" + kategoriFiltreleme + "%"))
                .OrderBy(x => x.Tittle).ToList();



            if (tittleSiralama == "asc")
            {
                blogs = blogs.OrderBy(x => x.Tittle).ToList();
            }
            else if (tittleSiralama == "desc")
            {
                blogs = blogs.OrderByDescending(x => x.Tittle).ToList();
            }



            if (yayinFiltreleme == "true")
            {
                blogs = blogs.Where(x => x.Publish == true).ToList();
            }
            else if (yayinFiltreleme == "false")
            {
                blogs = blogs.Where(x => x.Publish == false).ToList();
            }



            double kayitSayisi = Convert.ToDouble(blogs.Count());
            int sayfaSayisi = Convert.ToInt32(Math.Ceiling(kayitSayisi / 5));

            ViewBag.SayfaSayisi = sayfaSayisi;
            ViewBag.OncekiSayfa = sayfa == 1 ? 1 : sayfa - 1;
            ViewBag.SonrakiSayfa = sayfa == sayfaSayisi ? sayfaSayisi : sayfa + 1;
            ViewBag.Aranan = aranan;
            ViewBag.Sayfa = sayfa;
            ViewBag.TittleSiralama = tittleSiralama;
            ViewBag.Kategoriler = db.Categories.ToList();
            ViewBag.Etiketler = db.Tags.ToList();
            ViewBag.KategoriFiltreleme = kategoriFiltreleme;
            ViewBag.YayinFiltreleme = yayinFiltreleme;


            blogs = blogs.Skip((sayfa - 1) * 5)
                .Take(5).ToList();

            return View(blogs);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var db = new SqlContext();

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Tags = db.Tags.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Create(BlogCreate blogCreate)
        {
            var db = new SqlContext();

            if (ModelState.IsValid)
            {
                var blog = new Blog();

                if (blogCreate.Publish == "true")
                {
                    blog.Publish = true;
                }
                else if (blogCreate.Publish == "false")
                {
                    blog.Publish = false;
                }

                blog.PublishDate = DateTime.Now;
                blog.Tittle = blogCreate.Tittle;
                blog.Content = blogCreate.Content;
                blog.BlogCategoryId = blogCreate.BlogCategoryId;

                var tags = db.Tags.Where(x => blogCreate.BlogTagsId.Contains(x.Id)).ToList();
                blog.BlogTags.AddRange(tags);


                db.Blogs.Add(blog);
                db.SaveChanges();


                ModelState.Clear();
                ViewBag.message = "Kayıt başarılı";

            }

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Tags = db.Tags.ToList();

            return View();
        }

        [HttpGet]
        public IActionResult BlogAssignTag(int id)
        {
            var db = new SqlContext();

            var blog = db.Blogs.Include(x => x.BlogCategory)
                .Include(x => x.BlogTags).FirstOrDefault(x => x.Id == id);

            ViewBag.Tags = db.Tags.ToList();

            return View(blog);
        }

        [HttpPost]
        public IActionResult BlogAssignTag(int[] tagsId, int blogId)
        {
            var db = new SqlContext();

            var blog = db.Blogs.Find(blogId);
            var tags = db.Tags.Where(x => tagsId.Contains(x.Id)).ToList();
            blog.BlogTags.AddRange(tags);
            db.SaveChanges();


            ViewBag.Tags = db.Tags.ToList();
            ViewBag.message = "Etiket başarı ile kaydedildi.";


            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var db = new SqlContext();
            var blog = db.Blogs.Find(id);


            return View(blog);
        }

        [HttpPost]
        public IActionResult Delete(Blog blog)
        {
            var db = new SqlContext();
            db.Blogs.Remove(blog);
            db.SaveChanges();


            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var db = new SqlContext();
            var blog = db.Blogs.Include(x => x.BlogCategory)
                .Include(x => x.BlogTags).FirstOrDefault(x => x.Id == id);

            ViewBag.BlogId = id;
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Tags = db.Tags.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Update(BlogCreate blogCreate, int blogId)
        {
            var db = new SqlContext();

            if (ModelState.IsValid)
            {
                //var eskiBlog = db.Blogs.Find(blogId);
                //eskiBlog.BlogTags.Clear();
                //db.SaveChanges();

                var blog = new Blog();
                blog.Id = blogId;

                if (blogCreate.Publish == "true")
                {
                    blog.Publish = true;
                }
                else if (blogCreate.Publish == "false")
                {
                    blog.Publish = false;
                }

                blog.PublishDate = DateTime.Now;
                blog.Tittle = blogCreate.Tittle;
                blog.Content = blogCreate.Content;
                blog.BlogCategoryId = blogCreate.BlogCategoryId;

                var tags = db.Tags.Where(x => blogCreate.BlogTagsId.Contains(x.Id)).ToList();
                blog.BlogTags.AddRange(tags);

                db.Blogs.Update(blog);
                db.SaveChanges();

            }

            return RedirectToAction("Index");
        }
    }
}

BlogApp/Controllers/CategoryController.cs
using BlogApp.Data;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            var db = new SqlContext();

            ViewBag.Categories = db.Categories.ToList();

            return View();
        }


        [HttpPost]
        public IActionResult Index(Category category)
        {
            var db = new SqlContext();

            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();

                ModelState.Clear();
                ViewBag.message = "Kategori başarı ile kayıt edildi.";

            }

            ViewBag.Categories = db.Categories.ToList();

            return View();
        }


        [HttpGet]
        public IActionResult Update(int id)
        {
            var db = new SqlContext();
            var c = db.Categories.Find(id);

            return View(c);
        }

        [HttpPost]
        public IActionResult Update(Category category)
        {
            if (ModelState.IsValid)
            {
                var db = new SqlContext();
                db.Categories.Update(category);
                db.SaveChanges();

                ModelState.Clear();
                ViewBag.message = "Güncelleme işlemi başarılı.";

            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var db = new SqlContext();
            var c = db.Categories.Find(id);

            return View(c);
        }

        [HttpPost]
        public IActionResult Delete(Category category)
        {

            var db = new SqlContext();
            db.Categories.Remove(category);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

BlogApp/Controllers/TagController.cs
using BlogApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace BlogApp.Controllers
{
    public class TagController : Controller
    {
        public IActionResult Index()
        {
            var db = new SqlContext();
            ViewBag.Tags = db.Tags.ToList();

            return View();
        }


        [HttpPost]
        public IActionResult Index(Tag tag)
        {
            var db = new SqlContext();

            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();

                ModelState.Clear();
                ViewBag.message = "Etiket başarı ile kayıt edildi.";

            }

            ViewBag.Tags = db.Tags.ToList();

            return View();
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var db = new SqlContext();
            var t = db.Tags.Find(id);

            return View(t);
        }

        [HttpPost]
        public IActionResult Update(Tag tag)
        {
            if (ModelState.IsValid)
            {
                var db = new SqlContext();
                db.Tags.Update(tag);
                db.SaveChanges();

                ModelState.Clear();
                ViewBag.message = "Etiket başarı ile güncellendi";
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var db = new SqlContext();
            var t = db.Tags.Find(id);

            return View(t);
        }

        [HttpPost]
        public IActionResult Delete(Tag tag)
        {
            var db = new SqlContext();
            db.Tags.Remove(tag);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

BlogApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand mx-5" asp-controller="Home" asp-action="Index">Admin Paneli</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Category" asp-action="Index">Kategori</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Tag" asp-action="Index">Etiket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Etiket" asp-action="Privacy">Kullanıcı</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Blog" asp-action="Index">Makale</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BlogApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>